server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: testuser
    password: testpass

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  http:
    encoding:
      charset: UTF-8

  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
    static-path-pattern: /resources/**

book-search:
  kakao-api:
    url: https://dapi.kakao.com/v3/search/book